### ISSUE TITLE
REST API for tranferring KIN from my wallet to a user's wallet?

### ISSUE THREAD

**Issue by ghost** [kinecosystem/kin-token#17]
Sorry for asking the question here. I couldn't find any more appropriate place.

I am developing a web app and would like to use KIN as the internal currency for it in which users get rewards in KIN and would be able to transfer their credit from the website (my wallet) to their own wallet. Is there any REST API that allows this for KIN?

**Comment by oryband** [comment]
Hey @fexon ! Thanks for the question. Please see the reply I posted on our subreddit here: https://www.reddit.com/r/KinFoundation/comments/7syuo5/api_for_transferring_kin_from_one_wallet_to/dtd0g2c/

Closing the issue here as it's not related to this repository.
