### ISSUE TITLE
DAY should be 24 * HOUR not 24 * 60

### ISSUE THREAD

**Issue by jmpmonteagudo** [kinecosystem/kin-token#18]
Hi,

In file /test/VestingTrustee.js, shouldn't it be:
`const DAY = 24 * HOUR;`
instead of:
`const DAY = 24 * 60;`
?

Thanks,
Jose

**Comment by oryband** [comment]
Referring to this line: https://github.com/kinfoundation/kin-token/commit/e5f1279235d9df535d5e14e2240db6dc21ad796f#diff-4a87f1a53291ae83fb69905d1b25d690R10

**Comment by oryband** [comment]
thanks for pointing this out @js0p !
